name: GitHub Action Lint

on:
  push:
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: lint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/v1.7.7/scripts/download-actionlint.bash)
          ./actionlint
        shell: bash
